package eu.europeana.metis.core.workflow;

import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Field;
import dev.morphia.annotations.Id;
import dev.morphia.annotations.Index;
import dev.morphia.annotations.IndexOptions;
import dev.morphia.annotations.Indexes;
import eu.europeana.metis.core.workflow.plugins.AbstractMetisPlugin;
import eu.europeana.metis.core.workflow.plugins.ExecutablePluginType;
import eu.europeana.metis.mongo.model.HasMongoObjectId;
import eu.europeana.metis.mongo.utils.ObjectIdSerializer;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.bson.types.ObjectId;
import tools.jackson.databind.annotation.JsonSerialize;

/**
 * Is the structure where the combined plugins of harvesting and the other plugins will be stored.
 * <p>
 * This is the object where the execution of the workflow takes place and will host all information regarding its execution.
 * <p>
 * Moving this class to another package would make mongo-morphia queries empty because of the className autogenerated value.
 */
@Entity
@Indexes({
    @Index(fields = {@Field("datasetId")}),
    @Index(fields = {@Field("workflowStatus")}),
    @Index(fields = {@Field("ecloudDatasetId")}),
    @Index(fields = {@Field("cancelledBy")}),
    @Index(fields = {@Field("startedBy")}),
    @Index(fields = {@Field("createdDate")}),
    @Index(fields = {@Field("startedDate")}),
    @Index(fields = {@Field("updatedDate")}),
    @Index(fields = {@Field("finishedDate")}),
    @Index(fields = {@Field("workflowStatus"), @Field("claimedByInstance"), @Field("createdDate")}),
    @Index(fields = {@Field("workflowStatus"), @Field("updatedDate")}),
    @Index(fields = {@Field("metisPlugins.id")}, options = @IndexOptions(disableValidation = true)),
    @Index(fields = {@Field("metisPlugins.startedDate")}, options = @IndexOptions(disableValidation = true)),
    @Index(fields = {@Field("metisPlugins.updatedDate")}, options = @IndexOptions(disableValidation = true)),
    @Index(fields = {@Field("metisPlugins.finishedDate")}, options = @IndexOptions(disableValidation = true))})
@Getter
@Setter
@NoArgsConstructor
public class WorkflowExecution implements HasMongoObjectId {

  @Id
  @JsonSerialize(using = ObjectIdSerializer.class)
  private ObjectId id;
  private String datasetId;
  private WorkflowStatus workflowStatus;
  private String ecloudDatasetId;
  private String cancelledBy;
  private String startedBy;
  private String claimedByInstance;
  private boolean cancelling;
  private ExecutablePluginType nextExecutablePluginType;

  private Instant createdDate;
  private Instant startedDate;
  private Instant updatedDate;
  private Instant finishedDate;

  private List<AbstractMetisPlugin<?>> metisPlugins = new ArrayList<>();

  public List<AbstractMetisPlugin<?>> getMetisPlugins() {
    return new ArrayList<>(metisPlugins);
  }

  public void setMetisPlugins(List<AbstractMetisPlugin<?>> metisPlugins) {
    this.metisPlugins = metisPlugins == null ? new ArrayList<>() : new ArrayList<>(metisPlugins);
  }
}
