package eu.europeana.metis.core.engine.sandbox;

import eu.europeana.metis.core.engine.base.DataRevision;
import eu.europeana.metis.core.engine.base.EngineTask;
import eu.europeana.metis.core.engine.base.EngineTaskKey;
import eu.europeana.metis.core.engine.base.task.input.DepublishInputDataEndpoint;
import eu.europeana.metis.core.engine.base.task.input.HttpHarvestInputDataEndpoint;
import eu.europeana.metis.core.engine.base.task.input.InputDataEndpoint;
import eu.europeana.metis.core.engine.base.task.input.OaiHarvestInputDataEndpoint;
import eu.europeana.metis.core.engine.base.task.input.SimpleIntermediateInputDataEndpoint;
import eu.europeana.metis.core.engine.base.task.input.TransformExternalInputDataEndpoint;
import eu.europeana.metis.sandbox.common.task.input.HttpHarvestInputMetadataRequest;
import eu.europeana.metis.sandbox.common.task.input.InputMetadataRequest;
import eu.europeana.metis.sandbox.common.task.input.OaiHarvestInputMetadataRequest;
import eu.europeana.metis.sandbox.common.task.input.SandboxTask;
import eu.europeana.metis.sandbox.common.task.input.SandboxTaskKey;
import eu.europeana.metis.sandbox.common.task.input.SimpleIntermediateInputMetadataRequest;
import eu.europeana.metis.sandbox.common.task.input.TransformExternalInputMetadataRequest;
import java.time.Instant;
import java.util.Arrays;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.stream.Collectors;
import lombok.Getter;

/**
 * Represents a task for the metis-sandbox processing engine that wraps and transforms task parameters for use in a metis-sandbox
 * task.
 */
@Getter
public class SandboxEngineTask extends EngineTask {

  SandboxTask sandboxTask = new SandboxTask();

  /**
   * Constructs an EngineTask with specified parameters, input data endpoint, and output data revision.
   *
   * @param parameters Map of EngineTaskKey and String values used to configure the task. Must not be null.
   * @param inputDataEndpoint InputDataEndpoint representing the input data source for the task. Must not be null.
   * @param outputDataRevision DataRevision representing the output data revision generated by the task. Must not be null.
   */
  protected SandboxEngineTask(Map<EngineTaskKey, String> parameters,
      InputDataEndpoint inputDataEndpoint,
      DataRevision outputDataRevision) {
    super(parameters, inputDataEndpoint, outputDataRevision);
    setParameters();
    setInputDataLocation();
    setOutputRevision();
  }

  private void setParameters() {
    Set<String> validKeys = Arrays.stream(SandboxTaskKey.values())
                                  .map(Enum::name)
                                  .collect(Collectors.toSet());

    Map<SandboxTaskKey, String> sandboxParameters =
        parameters.entrySet().stream()
                  .filter(entry -> validKeys.contains(entry.getKey().name()))
                  .collect(Collectors.toMap(
                      entry ->
                          SandboxTaskKey.valueOf(entry.getKey().name()),
                      Entry::getValue
                  ));
    sandboxTask.setParameters(sandboxParameters);
  }

  private void setInputDataLocation() {
    InputMetadataRequest inputMetadataRequest = switch (this.inputDataEndpoint) {
      case OaiHarvestInputDataEndpoint(String url, String set, String metadataPrefix, Instant from, Instant until, Integer stepSize) ->
          new OaiHarvestInputMetadataRequest(url, set, metadataPrefix, from, until, stepSize);
      case HttpHarvestInputDataEndpoint(String url, Integer stepSize) -> new HttpHarvestInputMetadataRequest(url, stepSize);
      case TransformExternalInputDataEndpoint(String xslt, String url, String sourceExecutionId, DataRevision inputRevision) ->
          new TransformExternalInputMetadataRequest(xslt, sourceExecutionId);
      case SimpleIntermediateInputDataEndpoint(String url, String sourceExecutionId, DataRevision inputRevision) ->
          new SimpleIntermediateInputMetadataRequest(sourceExecutionId);
      case DepublishInputDataEndpoint ignored ->
          throw new IllegalArgumentException("DepublishInputDataEndpoint is not supported for sandbox tasks");
    };
    sandboxTask.setInputMetadataRequest(inputMetadataRequest);
  }

  private void setOutputRevision() {
    //Not required.
  }
}
