package eu.europeana.metis.core.engine.base;

import eu.europeana.metis.core.engine.base.task.input.InputDataEndpoint;
import java.util.Map;
import java.util.Objects;

/**
 * Represents a task that can be submitted to a processing engine.
 */
public class EngineTask {
  protected final Map<EngineTaskKey, String> parameters;
  protected final InputDataEndpoint inputDataEndpoint;
  protected final DataRevision outputDataRevision;

  /**
   * Constructs an EngineTask with specified parameters, input data endpoint, and output data revision.
   *
   * @param parameters Map of EngineTaskKey and String values used to configure the task. Must not be null.
   * @param inputDataEndpoint InputDataEndpoint representing the input data source for the task. Must not be null.
   * @param outputDataRevision DataRevision representing the output data revision generated by the task. Must not be null.
   */
  protected EngineTask(
      Map<EngineTaskKey, String> parameters,
      InputDataEndpoint inputDataEndpoint,
      DataRevision outputDataRevision) {
    this.parameters = Objects.requireNonNull(parameters);
    this.inputDataEndpoint = Objects.requireNonNull(inputDataEndpoint);
    this.outputDataRevision = Objects.requireNonNull(outputDataRevision);
  }
}
